[package]
name = "x4kas-gui"
description = "Desktop GUI for monitoring Kaspa L1 nodes over wRPC"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
readme.workspace = true
publish.workspace = true

[[bin]]
name = "x4kas"
path = "src/main.rs"

[dependencies]
x4kas-core.workspace = true
anyhow.workspace = true
clap.workspace = true
tokio.workspace = true
dirs.workspace = true
eframe.workspace = true
serde.workspace = true
egui_extras.workspace = true
egui_term.workspace = true
